name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ github.ref_name }}
        body: |
          ## AutoCron ${{ github.ref_name }}
          
          Cross-platform task scheduler for Python with zero-setup automation.
          
          ### Installation
          ```bash
          pip install autocron==${{ github.ref_name }}
          ```
          
          ### What's New
          See the [full changelog](https://github.com/mdshoaibuddinchanda/autocron/compare/v1.0.0...${{ github.ref_name }})
        draft: false
        prerelease: false

  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      id-token: write  # Required for trusted publishing
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
